import type { Metadata } from 'next';
import { League_Spartan } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/sidebar';

const font = League_Spartan({
  preload: true,
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portfolio | Rajat Raghuvanshi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="view-transition" content="same-origin" />
      <body className={font.className}>
        <Sidebar />
        <main className="p-2 w-full">{children}</main>
      </body>
    </html>
  );
}
